server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: hoteles-service
              uri: lb://hoteles-service
              predicates:
                - Path=/api/v1/hoteles/**

            - id: productos-service
              uri: lb://productos-service
              predicates:
                - Path=/api/v1/productos/**

            - id: usuarios-service
              uri: lb://usuarios-service
              predicates:
                - Path=/api/v1/usuarios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/